// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var greeting = "Hello World";

var multilineGreeting = "Hello\nWorld";

var greetingResult = greeting + " " + multilineGreeting;

console.log(greetingResult);

console.log("Text: " + greeting + "");

console.log("a"[0]);

console.log(String(1));

var r = /b/g;

console.log(2.1 + 3.2);

var x = Math.random();

console.log(x);

var firstLetterOfAlphabet = /* 'a' */97;

exports.greeting = greeting;
exports.multilineGreeting = multilineGreeting;
exports.greetingResult = greetingResult;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.r = r;
exports.x = x;
/*  Not a pure module */
