// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

var greeting = "Hello World";

var multilineGreeting = "Hello\nWorld";

var greetingResult = greeting + " " + multilineGreeting;

console.log(greetingResult);

console.log("Text: " + greeting + "");

console.log("a"[0]);

console.log(String(1));

var r = /b/g;

console.log(2.1 + 3.2);

var x = Math.random();

console.log(x);

var ageAndName = [
  24,
  "Lil' Rescript"
];

console.log(ageAndName);

var me = {
  age: 4,
  name: "Doe"
};

var newrecord = Caml_obj.obj_dup(me);

newrecord.age = 5;

console.log(newrecord);

console.log(undefined);

var maybePersonType = "Human";

var newrecord$1 = Caml_obj.obj_dup(me);

newrecord$1.personType = maybePersonType;

console.log(newrecord$1);

var isRescript;

isRescript = false;

console.log(isRescript);

var personTypeWasSet = newrecord$1.personType !== undefined;

console.log(personTypeWasSet);

var firstLetterOfAlphabet = /* 'a' */97;

var name = "Doe";

var meNextYear = newrecord;

var human = newrecord$1;

exports.greeting = greeting;
exports.multilineGreeting = multilineGreeting;
exports.greetingResult = greetingResult;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.r = r;
exports.x = x;
exports.ageAndName = ageAndName;
exports.me = me;
exports.name = name;
exports.meNextYear = meNextYear;
exports.maybePersonType = maybePersonType;
exports.human = human;
exports.isRescript = isRescript;
exports.personTypeWasSet = personTypeWasSet;
/*  Not a pure module */
